name: Container Build Test

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build container for testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2.4.0

      - name: Set up QEMU
        id: qemu
        if: success()
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64 

      - name: Set up Docker Buildx
        id: buildx
        if: success()
        uses: docker/setup-buildx-action@v2

      - name: Build container
        id: build
        if: success()
        uses: docker/build-push-action@v3
        with: 
          context: .
          file: ./Dockerfile
          platforms: amd64
          tags: aessing/minecraft-bedrock:container-build-test-${{ github.RUN_NUMBER }}
